import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://paintswitch.com",
      lastModified: "2026-08-14",
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: "https://paintswitch.com/alexandria-va",
      lastModified: "2026-08-14",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/arlington-va",
      lastModified: "2026-08-14",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/chevy-chase-village-md",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/mclean-va",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/potomac-md",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/vienna-va",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/fairfax-station-va",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/bethesda-md",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/great-falls-va",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/oakton-va",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/alexandria-va-interior-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/alexandria-va-exterior-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/alexandria-va-cabinet-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/alexandria-va-commercial-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/arlington-va-interior-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/arlington-va-exterior-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/arlington-va-cabinet-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/arlington-va-commercial-painting",
      lastModified: "2026-09-06",
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: "https://paintswitch.com/service-areas",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://paintswitch.com/interior-painting",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/exterior-painting",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/cabinet-painting",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/commercial-painting",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://paintswitch.com/guides",
      lastModified: "2026-08-22",
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://paintswitch.com/how-to-choose-interior-paint-colors",
      lastModified: "2026-08-22",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/exterior-paint-maintenance-guide",
      lastModified: "2026-08-22",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/what-affects-interior-painting-cost",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/what-affects-exterior-painting-cost",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/what-affects-cabinet-painting-cost",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/alexandria-va-painting-guide",
      lastModified: "2026-09-05",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/arlington-va-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/chevy-chase-village-md-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/mclean-va-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/potomac-md-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/vienna-va-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/fairfax-station-va-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/bethesda-md-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/great-falls-va-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/oakton-va-painting-guide",
      lastModified: "2026-09-06",
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: "https://paintswitch.com/privacy",
      lastModified: "2026-08-22",
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: "https://paintswitch.com/terms",
      lastModified: "2026-08-09",
      changeFrequency: "yearly",
      priority: 0.2,
    },
  ];
}
